sudo: required
dist: trusty

language: cpp
compiler: g++
git:
    submodules: false

install:
    - sudo apt-get install libprotobuf-dev protobuf-compiler libprotoc-dev

script:
    - ./build_travis.sh && ./build.sh
