sudo: required
dist: trusty
language: cpp
compiler:
- g++
- clang
os:
- linux
- osx
git:
  submodules: false
env:
  global:
    secure: "RaoaQknXip+3VBxJULlgI9lVVblqfQQccgqTdJrsNwm6NHpHAyG3AoMzI930ecj9dNHQHGLpovlQWu91CEURYLJWNxk/f+GVZoTYVeppytwn50W0JoGjUZKq204kt2LSioezTf63LbawHH0vy3R5OLNvAaloTVqL/2RUOqbEuMbohNCDWvukf6oIjm//6xtP2v+EStgDcBi5xDumMMTUYwUuQN/mOogOyeJlez4J6vtfdWhf0GKYCdoq2vr3mmO2GESDoenhsihl+nICKRfQDN1peqG3HOK8/Hl05HcJGaG0TftCsGQpwIZ/n8NzxuS1JetxSsEOqjIs1mNTCDJFa5psMs0reFkTbZnLa7MlD0wt1IuYSxVGS4oHJ4owOfGhU1cUiRjhELtolCx9N8sflUOtnQC+14VUgwDz9vHzIrz6ncKOObH0dQbJexJYIUBffStgBYu3GOD/MuCzmczsb8l7bpbvhcBGqSWc2oezP0mf8ytlWGRMQ1Vst1ySY8dY0zA2Zk3IYvRrPBrnZb3b+HreZ8FVR4yKHSK+5XK37Vr5Xlag1y9qlCrkBJEDdwKGAKFBtW4N+GrI4Emj+T6oIBdQTJyS3axTGVUcEl/+9a+uBrUv3vuTs8QJFR4QuqdQ4Mj5YhKdK2QWPzmhr5+vIupdevIuhiu0W9nRYDDkoUM="
before_script:
- ./build_travis.sh
script:
- ./build.sh
addons:
  coverity_scan:
    project:
      name: "QiumingLu/skywalker"
      description: "Build submitted via Travis CI"
    notification_email: mirantslu@gmail.com
    build_command_prepend: "rm -rf build"
    build_command: "./build.sh"
    branch_pattern: master
