sudo: required
dist: trusty
language: cpp
compiler:
- g++
- clang
os:
- linux
- osx
git:
  submodules: false
before_script:
- ./build_travis.sh
script:
- ./build.sh
addons:
  coverity_scan:
    project:
      name: "QiumingLu/skywalker"
      description: "Build submitted via Travis CI"
    notification_email: mirantslu@gmail.com
    build_command_prepend: "rm -rf build"
    build_command: "./build.sh"
    branch_pattern: master
